version: "3.8"

services:
  dev-environment:
    image: docker.pkg.github.com/zobairq/php-cloud-dev-environment/php-cloud-dev-environment:0.1
    ports:
      - 8443:8443
      - 8081:80
    container_name: php-dev
    environment:
      - PASSWORD=password
      - PORT=8443
